# Generated by Django 2.0.3 on 2018-05-30 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, verbose_name='用户名')),
                ('password', models.CharField(max_length=50, verbose_name='密码')),
                ('nickname', models.CharField(max_length=50, verbose_name='昵称')),
                ('head_pic', models.ImageField(default='head_img/default.jpg', upload_to='head_img/')),
            ],
        ),
    ]
